x-headless-client: &headless-client
  depends_on:
    server:
      condition: "service_started"
  image: mmo:latest
  entrypoint: ["headless_client"]
  environment:
    G_SERVER: "ws://server:8080"

services:
  server:
    build: .
    image: mmo:latest
    entrypoint: ["server"]
    environment:
      INTERACTABLES_CONFIG: "/data/interactables.json"
      ITEMS_CONFIG: "/data/items.json"
      NPCS_CONFIG: "/data/npcs.json"
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data

  client1:
    <<: *headless-client
